### ISSUE TITLE
Consider using the classList API for manipulating classNames

### ISSUE THREAD

**Issue by oliverjam** [fac25/week2-agencyProject-Patrick-Sumithra#17]
https://github.com/fac25/week2-agencyProject-Patrick-Sumithra/blob/b420506ab9c4d70a3260ffd79bd65db334226ba2/scripts/Navbar/nav.js#L12-L21

There's nothing wrong with this code (because it works!), but it is a little unclear exactly what's happening at first glance.

Dealing with `element.className` is a bit awkward as it is just a long string with all the classes. This is why browsers added the [`element.classList` API](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList). It actually has a `.classList.toggle()` method designed for just this use-case—it will check if a class is present and either add it or remove it.

**Comment by Sumithra-Suresh** [comment]
Thanks for pointing out the API. I have used the API to toggle between the class name.
