### ISSUE TITLE
Links need text labels

### ISSUE THREAD

**Issue by oliverjam** [fac25/week2-agencyProject-Patrick-Sumithra#21]
https://github.com/fac25/week2-agencyProject-Patrick-Sumithra/blob/b420506ab9c4d70a3260ffd79bd65db334226ba2/index.html#L40

I did a Lighthouse audit and it flagged that this link tag doesn't have a label. It's important for interactive elements to have labels so that users who can't see the icon know what's going to happen.

You could try using [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) to provide a non-visual label for assistive tech users.

**Comment by Sumithra-Suresh** [comment]
Added aria-label.
